### ISSUE TITLE
Rerank function giving RuntimeError: he number of subscripts in the equation (3) does not match the number of dimensions (2) for operand 1 and no ellipsis was given

### ISSUE THREAD

**Issue by John42506176Linux** [lightonai/pylate#57]
Pytorch version:
Version: 2.4.1

Full Error:
Code:
reranked_documents = rank.rerank(
    documents_ids=ids,
    queries_embeddings=queries_embeddings,
    documents_embeddings=documents_embeddings,
)
RuntimeError: einsum(): the number of subscripts in the equation (3) does not match the number of dimensions (2) for operand 1 and no ellipsis was given
![image](https://github.com/user-attachments/assets/d16809f7-7043-428a-92e9-cda3c3117cd8)

**Comment by NohTow** [comment]
Hello,

It seems that the embeddings you are feeding to the rerank function does not have a correct shape.
[You have a boilerplate here](https://lightonai.github.io/pylate/documentation/retrieval/#colbert-reranking) that shows how to encode your queries and documents to work with rerank.

Could you check if your code corresponds and if not, send the code to reproduce the issue.

**Comment by John42506176Linux** [comment]
Hi @NohTow,

Thanks for the assistance, I didn't realize that rerank and the retrieval had different syntaxes for passing documents, my mistake. :)
