### ISSUE TITLE
Is there any way to extend this to ColPali models as well?

### ISSUE THREAD

**Issue by aliozts** [lightonai/pylate#61]
Hi, first of all, thank you for the amazing work! This is more of a curiosity question, will this repository also extend to ColPali/ColQwen as well?

**Comment by NohTow** [comment]
Hello,
Thanks for your kind words!

This was the initial plan, yet after reviewing the [official ColPali repository](https://github.com/illuin-tech/colpali), it appeared that it is actually well written and pretty modular already (which makes the portage less useful than compared to Stanford-nlp).
Adding new base model should be fairly straightforward, as it only requires to add a modeling file (which should be very similar to the existing ones) and a processing one, which, unfortunately, is not really standardized across the different VLMs.
This is why, for the moment, it is very hard to build one additional layer of abstraction that would make it work with every VLMs possible, and ultimately require to add these specific processing files.

Was there a particular reason you wanted ColPali into PyLate (besides having an unified codebase obviously)?
I think @tonywu71 and @ManuelFay would be happy to help you add a new architecture or a missing feature!

**Comment by aliozts** [comment]
Hello, thanks for the prompt and detailed response!!

It was mostly to be able to utilize the API server in a unified codebase with capability of batch processing you are using.

**Comment by NohTow** [comment]
Ah, this!
I pinged the authors of ColPali during the release, and I know for a fact that they are working on a similar feature for ColPali!
In the mean time, I do not know how fluent in code you are, but the server code is pretty simple, making it work with ColPali should be quite straightforward!

**Comment by aliozts** [comment]
I'm alright in the code bit. I'll check the codebase in the weekend if I can, I cannot promise that I'll be able to deliver something but if I can make the time I'll try to contribute. thank you so much!
